<?php

function broken_link_checker_schema() {
  $schema['broken_links'] = [
    'description' => 'Stores broken links.',
    'fields' => [
      'id' => [
        'type' => 'serial',
        'not null' => TRUE,
      ],
      'nid' => [
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ],
      'url' => [
        'type' => 'varchar',
        'length' => 1000,
        'not null' => TRUE,
      ],
      'status_code' => [
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
      ],
    ],
    'primary key' => ['id'],
  ];

  return $schema;
}
